[tool.poetry]
name = "toml项目管理实践-py"
version = "0.1.0"
description = ""
authors = ["解大劦 <9727005@qq.com>"]
readme = "README.md"
packages = [{include = "toml项目管理实践"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
